### ISSUE TITLE
Getting the coverage

### ISSUE THREAD

**Issue by r3bb1t** [tandasat/Hypervisor-101-in-Rust#5]
I'd like to get the coverage of the .efi file like [here](https://github.com/tandasat/Hypervisor-101-in-Rust/tree/main/tests#ida-python-files):

I don't really understand how to do it. I ran the following command:

> cargo xtask bochs-amd | tee coverage.log

Then i loaded the **refind_x64_signed_at_0xDD15000.efi** into the Ida 7.6 and fed it the script **ida_highlight_coverage.py** (file -> Script File...) and provided the coverage.log. I got the following error:

![image](https://user-images.githubusercontent.com/49586603/234786943-a3451c6b-7aaf-48e8-b2d9-d04252247c47.png)

And the problem is, that it's trying to highlight the addreses starting with like 0xdd2.... 

While in Ida, my file is loaded at 0x00 adress. Maybe i need to rebase it, but how would i know to which adress?

I think we really need the more in-depth documentation about getting the coverage about getting the coverage. There are not many such materials in the internet and it would be really useful to have one documented.  

Also don't forget to explain how can we prepare our own efi files for getting the coverage from them.

**Comment by r3bb1t** [comment]
Also note, that you can't launch vmware from wsl on windows because of the Hyper-V i guess. 

I was able to launch the hypervisor by typing the following in cmd (with administrator privs) and rebooting:

> bcdedit /set hypervisorlaunchtype off

It will make **WSL** unusable, but will let us run the hypervisor in Vmware.
Otherwise, i am getting errors from Vmware and it refuses to launch with AMD-V support.


When we will decide to get back to **WSL**, we will type the following and reboot:

> bcdedit /set hypervisorlaunchtype auto

**Comment by tandasat** [comment]
You need to rebase the image to 0xDD15000. I will update https://github.com/tandasat/Hypervisor-101-in-Rust/blob/main/tests/README.md to mention that you need to rebase the image.

Taking coverage from another EFI is not possible because I did not include code to take a snapshot. I filed a https://github.com/tandasat/Hypervisor-101-in-Rust/issues/6 for a separate discussion.  

> we really need the more in-depth documentation about getting the coverage about getting the coverage.

Can you share how do you think explanations can be improved? 
https://tandasat.github.io/Hypervisor-101-in-Rust/vm-introspection-for-fuzzing/basic-block-coverage-tracking-through-patches.html
This page explains the concept with a plenty of links to other learning resources, which I think reasonable amount of information. Certainly enough if you look into those external projects. But I am open for improvement and ideas,

Re: VMware. You are right. I will update BUILDING.md to mention the need of disabling Hyper-V. QA of instructions was lighter for VMware, as it was an optional setup. Thanks for calling it out.

**Comment by r3bb1t** [comment]
So, i rebased the program


![image](https://user-images.githubusercontent.com/49586603/234951080-062dc7c6-9927-4533-a92f-b7c69c2c5a9f.png)


Tried to paint the coverage

![image](https://user-images.githubusercontent.com/49586603/234951436-74cc15c5-9f80-4a99-840e-c6a49278d36a.png)


In result, there are no basic blocks painted, even tho the script says that they have been highlighted


P.s I attached my coverage files below

[serial.log](https://github.com/tandasat/Hypervisor-101-in-Rust/files/11346609/serial.log)
.
[coverage.log](https://github.com/tandasat/Hypervisor-101-in-Rust/files/11346612/coverage.log)



> Can you share how do you think explanations can be improved?

My bad, the documentation is quite decent. What i meant by my question, is that we need more info on how to load the snapshot or/and whole efi file and how to instrument it to visualise it's coverage. 



### Edit:

The script highlights the executed blocks succesfully, but it seems that it also misses some functions, because the **ModuleEntryPoint** function is not highlighted, so it assumes that it was never executed.


![image](https://user-images.githubusercontent.com/49586603/234956286-c58f5dfd-2044-42ca-8500-14ab1212ba1b.png)

**Comment by tandasat** [comment]
Glad to hear it is working after rebase. The entry point is not highlighted because the snapshot is taken right before image parsing logic. In your log, `rip: 0xdd24e73,` you can find the initial guest RIP. 

with [e364868](https://github.com/tandasat/Hypervisor-101-in-Rust/commit/e364868687c95cd0e6bc2e6b5d8cbd064d721973), I have added a comment about need of rebase, as well as a GIF demo in this page.
https://github.com/tandasat/Hypervisor-101-in-Rust/blob/main/course/src/vm-introspection-for-fuzzing/demo-coverage-tracking.md

also with [a374c6d](https://github.com/tandasat/Hypervisor-101-in-Rust/commit/a374c6de4de376cd17415c50feee0e202fdd55ce), I mentioned the need of disabling Hyper-V.

With that, I am going to close this issue with that. If you have further suggestions, feel free to reopen it and comment.
